---
AWSTemplateFormatVersion: 2010-09-09
Description: Batch job definition
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: ssr
  EcrRepositoryName:
    Description: Set the ECR repository name.
    Type: String
    Default: executor-on-s3
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: s3-bucket-and-iam-resources
Resources:
  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Ref EcrRepositoryName
      Type: container
      ContainerProperties:
        Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrRepositoryName}
        Command:
          - --version
        JobRoleArn:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchJobIamRoleArn
        ExecutionRoleArn:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchJobExecutionIamRoleArn
        Environment:
          - Name: MOUNT_S3_BUCKET
            Value:
              Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-S3Bucket
          - Name: MOUNT_S3_DIRECTORY
            Value: /mnt/s3
        ReadonlyRootFilesystem: false
        Privileged: true
        User: root
        ResourceRequirements:
          - Type: VCPU
            Value: 1
          - Type: MEMORY
            Value: 2048
        # NetworkConfiguration:
        #   AssignPublicIp: DISABLED
        # EphemeralStorage:
        #   SizeInGiB: 200
        # FargatePlatformConfiguration:
        #   PlatformVersion: LATEST
        LinuxParameters:
          Devices:
            - ContainerPath: /dev/fuse
              HostPath: /dev/fuse
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Sub /aws/batch/${ProjectName}-batch-job
            awslogs-stream-prefix: !Ref EcrRepositoryName
      PropagateTags: true
      PlatformCapabilities:
        - EC2   # FARGATE
      RetryStrategy:
        Attempts: 5
        EvaluateOnExit:
          - Action: RETRY
            OnStatusReason: Host EC2*
          - Action: EXIT
            OnReason: '*'
      Timeout:
        AttemptDurationSeconds: 1209600
      Tags:
        Name: !Ref EcrRepositoryName
        ProjectName: !Ref ProjectName
Outputs:
  BatchJobDefinition:
    Value: !Ref BatchJobDefinition
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobDefinition
